<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="picasa, image hosting, free photo sharing and video sharing. Upload your photos and share them with friends and family."/>
<meta name="keywords" content="picasa, album, free image hosting, image hosting, video hosting, photo image hosting site"/>
<meta name="Báo Vi Phạm" content="Yahoo: totnhat_hotro - Email: Baycgup@gmail.com"/>
<title>Up Ảnh Free - totnhat.tk</title>
<script type="text/javascript" src="script.js"></script> 
<link rel="stylesheet" href="style.css" type="text/css" />
<style type="text/css">
<!--
.style1 {color: #000}
-->
</style>
</head>
<body>
<div id="wrapper">
	<div class="block">

        <div>
<font color="red"><strong>Trước khi upload ảnh, cần lưu ý rằng: Do ảnh được upload tự do không cần tài khoản, nên hình ảnh sẽ chỉ bị xóa khi:</strong>
            <br />1. Vi phạm điều khoản, qui định pháp luật Việt Nam & Google Picasa
            <br />2. Gây tổn hại đến người khác hoặc xóa theo yêu cầu của chủ sở hữu (<i>phải chứng minh được</i>) trong trường hợp <i>thực sự cần thiết</i>.
</font>
        </div>
         <div>
            <br />Chọn 1 hoặc nhiều hình ảnh từ: 
            <a href="?op=upload">Máy tính</a> hoặc <a href="?op=transfer">URL</a> | Đóng dấu ảnh: <input type="radio" name="watermark" id="watermark" onclick="setWatermark(true);" checked="checked"/> Có <input type="radio" name="watermark" onclick="setWatermark(false);"/> Không
        </div>

		<? if(!$_GET['op'] || $_GET['op'] == 'upload'){?>      
<br />
            <div id="inputfile" style="height:20px;width:250px;">
                 <div style="float: left;">
                    <input type="text" style="height:23px;border:1px solid #ccc;width:170px;">
                </div>
                <div style="float: left;" id="flash_upload"></div>
            </div>
            <script>setWatermark(true);</script>
		<? }else{?>

            Enter Url<br />
            <textarea id="listurl" name="listurl" style="height:150px;width:100%" ></textarea>
            <input type="button" onclick="clearlist();transfer();" value="Transfer"/> 	
        <? }?>

    </div>    
   	<div class="block">
        <div id="result"></div>
        <div id="loading"></div>
        <div id="getcode" style="display:none">
            <div>
                <a href="javascript:showcode('bbcode');">Chèn vào Forum</a> | 
                <a href="javascript:showcode('html');">Chèn vào Website</a> | Link ảnh trực tiếp: 
                <a href="javascript:showcode('1600');">Fullsize</a> | 
				<a href="javascript:showcode('120');">120x</a> | 
				<a href="javascript:showcode('150');">150x</a> | 
				<a href="javascript:showcode('200');">200x</a> | 
				<a href="javascript:showcode('250');">250x</a> | 
				<a href="javascript:showcode('300');">300x</a> | 
				<a href="javascript:showcode('480');">480x</a> | 
				<a href="javascript:showcode('640');">640x</a> | 
				<a href="javascript:showcode('800');">800x</a> |
				<a href="javascript:showcode('1200');">1200x</a>
             </div>
            <div><textarea id="showcode" style="height:130px;width:100%" onclick="this.select();"></textarea></div>
        </div>
     </div>   
	<div class="block">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script language="JavaScript" src="jquery.tinycarousel.min.js"></script>
			<div class="top_img" id="slider-code">
            	<h3>Ảnh mới được upload:</h3>
            	<a href="#" class="back prev"></a>
                <div class="slide viewport" id="slide">
					<ul class="overview">
<?php
	require("./config.php");
	require_once 'Zend/Loader.php';
	Zend_Loader::loadClass('Zend_Gdata');
	Zend_Loader::loadClass('Zend_Gdata_ClientLogin');
	Zend_Loader::loadClass('Zend_Gdata_Photos');
	Zend_Loader::loadClass('Zend_Http_Client');	
	
	$serviceName = Zend_Gdata_Photos::AUTH_SERVICE_NAME;
	$client = Zend_Gdata_ClientLogin::getHttpClient($user, $pass, $serviceName);

	// update the second argument to be CompanyName-ProductName-Version
	$gp = new Zend_Gdata_Photos($client, "Google-DevelopersGuide-1.0");
	$query = $gp->newUserQuery();

	// indicate the user's feed to retrieve
	$query->setUser("default");

	// set to only return photos
	// the default kind value for a user feed is to include only albums
	$query->setKind("photo");

	$query->setMaxResults($images_in_slide);

    // we're passing null for the username, as we want to send
    // additional query parameters generated by the UserQuery class
    $userFeed = $gp->getUserFeed(null, $query);

    // because we specified 'photo' for the kind, only PhotoEntry objects 
    // will be contained in the UserFeed
    foreach ($userFeed as $photoEntry) {
		if ($photoEntry->getMediaGroup()->getThumbnail() != null) {
		  $mediaThumbnailArray = $photoEntry->getMediaGroup()->getThumbnail();
		  $firstThumbnailUrl = $mediaThumbnailArray[1]->getUrl();
		}
		$link = $photoEntry->getLink('alternate')->getHref();
		$title = $photoEntry->getTitle()->getText();
        echo <<<abc
<li><a href="$link" target="_blank" title="$title">

						<table><tr><td style="height: 144px; width: 144px; vertical-align: bottom; text-align: center;">
							<img style="max-height: 144px; max-width: 144px" src="$firstThumbnailUrl" alt="$title" border="0" />
						 </td></tr></table>	
						</a>
						</li>		
abc;
    }
?>
</ul>
                </div>
            
            	<a href="#" class="next"></a>
            	<div class="clear"></div>
        	</div>

		<script language="JavaScript">
		$(document).ready(function() {
			$(".overview").find("img").error(function() {
				$(this).parentsUntil(".overview").remove();
			});
			if ( $(".overview").children().length == 0 )
				$('#slider-code').remove();
			$('#slider-code').tinycarousel({ display: 1, interval:true });
		});
		</script>
	</div>	 
</div><!--/#wrapper-->
<div align="center">© 2013 - <a href="http://baychup.tk/" target="_blank" title="miễn phí.">Cộng đồng Bay chụp và Đo vẽ ảnh</a></div>
</body>
</html>